# spring:
#   flyway:
#     baseline-version: 1
#     baseline-on-migrate: true

logging:
  level:
    com:
      saw:
        sns:
          sms:
            web: DEBUG
          email:
            web: DEBUG

server:
  port: 12013

# aws:
#   region: ${SNS_AWS_REGION}
