# spring:
#   flyway:
#     baseline-version: 1
#     baseline-on-migrate: true
#     enabled: false

logging:
  level:
    com:
      saw:
        sns:
          sms:
            web: DEBUG

server:
  port: 12013
