spring:
  config:
    activate:
      on-profile:
      - prod
      - default
# spring:
#   flyway:
#     baseline-version: 1
#     baseline-on-migrate: true

push:
  app:
    s3:
      config:
        bucket: ${AWS_S3_BUCKET_CONFIG}
        file: ${AWS_FILE_CONFIG}

logging:
  level:
    com:
      saw:
        sns:
          sms:
            web: ERROR
            service: ERROR
          email:
            web: ERROR
            service: ERROR
          push:
            web: ERROR
            service: ERROR

server:
  port: 12013

# aws:
#   region: ${SNS_AWS_REGION}