name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Ensure execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew test --no-daemon


    - name: Build with Gradle
      run: ./gradlew build -x test --no-daemon
